// Generated by Wrangler by running `wrangler types`

interface Env {
    SUPABASE_URL: string;
    D1_CACHESTORE_TABLE_NAME: "supacache";
    D1_CACHESTORE_ENCRYPTION_KEY: string;
    SERVICE_AUTH_KEY: string;
    SUPACACHE_DB: D1Database;
}
